ASFIPSEC: Fixing miscellaneous error
In this patch following things are done.
1. GET_CACHE_ALLIGNED uint is changed to uintptr_t.
2. Removing compilation errors for IPSEC debug case.
3. Temp fix in case OutSA not found.
4. Fix for bug in asfctrl_xfrm_add_outsa, sa_id instead of outSA.ulSAContainerIndex.
5. pSelList = pSA->pHeadSelList; removes crash on adding AH policy.
6. SECFP_ENC_NONE solves the InvalidAuthEncAlgo problem.

Change-Id: I1414a5a563cece2c860d9931672e1609a9f14a5f
Signed-off-by: Sahil Malhotra <sahilmalhotra@freescale.com>
CR:ENGR00331411
Reviewed-on: http://git.am.freescale.net:8181/18511
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>