ASF ARM Porting: Removing compilation error of ASF without rx tx patch in linux.
RX TX optimisation patch (which is to include file asf_gianfar.c
and asf_gianfar.h in linux) is not included in linux.
Hence, asf_ginafar.h header file is removed from ASF and
using gfar_start_xmit() in minimal mode for dev hard xmit.

Signed-off-by: Ganga Negi <ganga.negi@freescale.com>
Change-Id: I4d92e6ff16ffd5810a3453106a9499dc81226778
CR:ENGR00327824
Reviewed-on: http://git.am.freescale.net:8181/17158
Reviewed-by: Hemant Agrawal <hemant@freescale.com>
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>
(cherry picked from commit 53d30824d0c0ad474e7e1152d454494efc08a34b)
Reviewed-on: http://git.am.freescale.net:8181/22625
Reviewed-on: http://git.am.freescale.net:8181/29930