asf_qos: Patch to fix the compilation error in asf_qos.
This patch fixes the compilation error in asf_qos module
when compiled for DPAA platform. The issue was because
the mac.h file is no longer part of dpaa_eth.h

Signed-off-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Change-Id: I89c8c9052988cf373980420d40b5f5eaf491acb7
----
CQ:ENGR00298539
Reviewed-on: http://git.am.freescale.net:8181/8714
Reviewed-by: Rajan Gupta <rajan.gupta@freescale.com>
Tested-by: Rajan Gupta <rajan.gupta@freescale.com>
(cherry picked from commit 84dc448d8d019619c5ac875ffd3a815cdbf9e3e1)
Reviewed-on: http://git.am.freescale.net:8181/8787