asf_ipsec: Patch to fix the issue of errors introduced while removing the compilation errors.
This patch resolves the errors in the IPsec processing
introduced while removing the compilation warnings in the system.

Signed-off-by: Sandeep Malik <Sandeep.Malik@freescale.com>

Change-Id: If94308e64deba53edd00fa43f78a6be5ba6b2932
CR:ENGR00261837
Reviewed-on: http://git.am.freescale.net:8181/17132
Reviewed-by: Hemant Agrawal <hemant@freescale.com>
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>