ASFIPSEC: Removing compilation error after adding patch "Incorrect handling of decrementing TTL of inner IP header".
In patch "Incorrect handling of decrementing TTL of inner IP header",
lines decrementing TTL value in function secfp_inAHComplete() should
be removed because inner IP header TTL is not decremented while decapsulation.

Signed-off-by: Ganga Negi <ganga.negi@freescale.com>
CR: ENGR00315820
Change-Id: Ib71cefcefd7bb7cdad2b5fa22ba5ed45b5b8e9c2
Reviewed-on: http://git.am.freescale.net:8181/14827
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>