ASF: Removing compilation error because of updation in linux structure 'dpa_priv_s'.
The DPAA eth driver has been updated to merge the recycle and confirmation 
queues.To achieve this the 'recycle_fqs' has been removed from 'dpa_priv_s' 
structure. This member was being used in ASF and since the driver has 
been updated so the ASF compilation fails. The ASF code has been updated
as per the latest driver's convention.

Signed-off-by: Ganga Negi <ganga.negi@freescale.com>
Change-Id: I388abd23a377473b85d865da416fa875826c5ffb
CR:ENGR00330798
Reviewed-on: http://git.am.freescale.net:8181/18257
Reviewed-by: Arun Pathak <arun.pathak@freescale.com>
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>