Revert "ASF_QOS: Removing compilation error."
In ls1-dev while submitting patch we were getting checkpatch
errors and hence to remove it we used struct instead of typedefs
and perfomed corresponding changes in ASF too.
But linux-devel has no such issues, hence we have to revert
changes in ASF.

This reverts commit d40ec6b3bf02dc68ce1d8a24425f042573f13254.

Signed-off-by: Ganga Negi <ganga.negi@freescale.com>
CR:ENGR00339766
Change-Id: I717fc8caa455b7e4e7ee5a5d4085ba3ee8040c5a
Reviewed-on: http://git.am.freescale.net:8181/23778
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>