ASF: Patch to fix compilation errors.
This patch fix the compilation errors in ASF code with latest
changes in DPAA and CAAM driver code in linux kernel.

CQ-Id: ENGR276698
Change-Id: I6039d47250bde1858e20341a39b0dfb6e1a7b48f
Signed-off-by: Nikhil Agarwal <nikhil.agarwal@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/4416
Reviewed-by: Malik Sandeep-B02416 <Sandeep.Malik@freescale.com>
Reviewed-by: Gupta Rajan-B15745 <rajan.gupta@freescale.com>
Tested-by: Gupta Rajan-B15745 <rajan.gupta@freescale.com>