ASF_QOS: Removing compilation error.
There are checkpatch errors in Linux for adding new
typedefs. typedefs are removed and struct is used.
Corresponding structs are changed in ASF also.

Change-Id: Idc651cadf30d4a02b0539e496e7de0affc864dcd
Signed-off-by: Nikhil Agarwal <Nikhil.Agarwal@freescale.com>
Signed-off-by: Sahil Malhotra <sahilmalhotra@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/17707
Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>
Reviewed-on: http://git.am.freescale.net:8181/22645